### ISSUE TITLE
This tool is not reproducible in Windows

### ISSUE THREAD

**Issue by MartyMacGyver** [arduino-org/arduino-tool-stm32load#1]
Despite several attempts using go1.8.1 (windows/amd64) the Windows version of this tool is not currently reproducible. It appears that the version being shipped is built against the very old go1.2.1. This makes it difficult to debug or even reproduce in a current environment as dependencies (e.g., https://github.com/mattn/go-shellwords) have been upgraded as well in the interim.

**Comment by artynet** [comment]
hello @MartyMacGyver,

please take a look at the release page. I have just rebuilt the Go executables with the latest binary version of the compiler (v1.8.3)....hope that this helps ! 

Best, Arturo

**Comment by MartyMacGyver** [comment]
It works now - I'm not sure what went wrong before but I'm able to clone the repo and build the tool OK with Go 1.8.3. Good to have the current release version here so thank you for that!

**Comment by artynet** [comment]
Good to know @MartyMacGyver ! Have fun and report any other issue if occurs ;)

Best, Arturo
